# See https://github.com/actions/setup-dotnet
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - aiwa-api

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Add private NuGet package feed
        shell: bash
        run:
          dotnet nuget add source --username ltlian --password ${{ secrets.NUGET_API_KEY }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ltlian/index.json"

      - name: dotnet build
        run: dotnet build src/AIWA.API.csproj -c Release

      - name: dotnet test
        run: dotnet test -c Release --logger trx --results-directory "TestResults"
        
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results
          path: TestResults
          retention-days: 1
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

      # The Azure Web App service runs the risk of trying to run the app using .NET7. In this case, it might be necessary to deploy as self-contained and with the appropriate rid.
      # See https://learn.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained
      # Example: dotnet publish src/AIWA.API.csproj --self-contained -r linux-x64 -c Release -o ${{env.DOTNET_ROOT}}/out
      - name: dotnet publish
        run: dotnet publish src/AIWA.API.csproj -c Release -o ${{env.DOTNET_ROOT}}/out

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/out
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'aiwa-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
